
#pragma once

#include <array>

#include <data/moves.h>
#include <data/species.h>

#include <battle/init.h>

namespace Init {
struct Set;
struct Config;
} // namespace Init

namespace SampleTeams {
// using Init::Set;
using Data::Moves;
using Data::Species;
using enum Moves;

constexpr std::array<std::array<Init::Set, 6>, 100> teams{
    std::array<Init::Set, 6>{
        Init::Set{Species::Jynx, {Blizzard, LovelyKiss, Psychic, Rest}},
        Init::Set{Species::Chansey, {IceBeam, Sing, SoftBoiled, Thunderbolt}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Explosion, HyperBeam}},
        Init::Set{Species::Rhydon,
                  {BodySlam, Earthquake, RockSlide, Substitute}},
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Lapras, {Blizzard, HyperBeam, Sing, Thunderbolt}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Counter, IceBeam, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Lapras, {Blizzard, HyperBeam, Sing, Thunderbolt}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, HyperBeam, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Rhydon,
                  {BodySlam, Earthquake, RockSlide, Substitute}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Lapras, {Blizzard, BodySlam, Sing, Thunderbolt}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, HyperBeam, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Lapras, {Blizzard, HyperBeam, Sing, Thunderbolt}},
        Init::Set{Species::Snorlax, {BodySlam, HyperBeam, Reflect, Rest}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, HyperBeam, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie,
                  {Psychic, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, MegaDrain, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Lapras, {Blizzard, HyperBeam, Sing, Thunderbolt}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Golem,
                  {Earthquake, Explosion, RockSlide, Substitute}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {IceBeam, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, MegaDrain, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Slowbro, {Amnesia, Psychic, Rest, ThunderWave}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Rest, SelfDestruct}},
        Init::Set{Species::Golem,
                  {Earthquake, Explosion, RockSlide, Substitute}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie,
                  {Psychic, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Rest, SelfDestruct}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie,
                  {Psychic, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, Reflect, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Jynx, {Blizzard, LovelyKiss, Psychic, Rest}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, HyperBeam, Psychic, SleepPowder}},
        Init::Set{Species::Rhydon,
                  {BodySlam, Earthquake, RockSlide, Substitute}},
        Init::Set{Species::Snorlax, {BodySlam, IceBeam, Reflect, Rest}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey, {IceBeam, Sing, SoftBoiled, ThunderWave}},
        Init::Set{Species::Gyarados,
                  {BodySlam, HydroPump, HyperBeam, Thunderbolt}},
        Init::Set{Species::Jolteon,
                  {DoubleKick, Rest, Thunderbolt, ThunderWave}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Lapras, {Blizzard, HyperBeam, Sing, Thunderbolt}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Rest, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Jynx, {Blizzard, LovelyKiss, Psychic, Rest}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Moltres, {Agility, FireBlast, FireSpin, HyperBeam}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Rest, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Chansey, {IceBeam, Sing, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Sandslash,
                  {Earthquake, RockSlide, Slash, SwordsDance}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Rest, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Jynx, {Blizzard, LovelyKiss, Psychic, Rest}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Explosion, HyperBeam}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Snorlax,
                  {Amnesia, Blizzard, BodySlam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Lapras, {Blizzard, HyperBeam, Sing, Thunderbolt}},
        Init::Set{Species::Snorlax, {BodySlam, HyperBeam, Reflect, Rest}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, HyperBeam, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Jolteon,
                  {DoubleKick, PinMissile, Thunderbolt, ThunderWave}},
        Init::Set{Species::Chansey, {IceBeam, Sing, SoftBoiled, ThunderWave}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Explosion, Rest}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Rest, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, HyperBeam, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Explosion, Rest}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Rhydon,
                  {BodySlam, Earthquake, RockSlide, Substitute}},
        Init::Set{Species::Starmie, {Recover, Surf, Thunderbolt, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Lapras, {Blizzard, HyperBeam, Sing, Thunderbolt}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Hypno, {Hypnosis, Psychic, Rest, ThunderWave}},
        Init::Set{Species::Articuno, {Agility, Blizzard, HyperBeam, IceBeam}},
        Init::Set{Species::Dugtrio, {Earthquake, RockSlide, Slash, Toxic}},
        Init::Set{Species::Kadabra,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Omastar, {Blizzard, BodySlam, HydroPump, Rest}},
        Init::Set{Species::Tentacruel, {Blizzard, HydroPump, Surf, Wrap}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Rhydon,
                  {BodySlam, Earthquake, RockSlide, Substitute}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Rest, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, HyperBeam, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, IceBeam, Reflect, Rest}},
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, HyperBeam, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {DrillPeck, Thunderbolt, ThunderWave, Toxic}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie,
                  {Psychic, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey, {Counter, IceBeam, Sing, SoftBoiled}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Explosion, Rest}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Rest, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, MegaDrain, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {Amnesia, BodySlam, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, IceBeam, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Lapras, {Blizzard, HyperBeam, Sing, Thunderbolt}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey, {IceBeam, Sing, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, HyperBeam, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Starmie,
                  {Psychic, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, HyperBeam, Thunderbolt}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Rest, SelfDestruct}},
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Lapras,
                  {Blizzard, BodySlam, ConfuseRay, Thunderbolt}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, MegaDrain, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, IceBeam, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, FireBlast, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Rhydon,
                  {BodySlam, Earthquake, RockSlide, Substitute}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Counter, Earthquake, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Jynx, {Blizzard, Counter, LovelyKiss, Psychic}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Snorlax, {Amnesia, Blizzard, BodySlam, Rest}},
        Init::Set{Species::Starmie, {Recover, Surf, Thunderbolt, ThunderWave}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Jynx, {Blizzard, LovelyKiss, Psychic, Rest}},
        Init::Set{Species::Alakazam, {Psychic, Recover, Reflect, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Rhydon,
                  {BodySlam, Earthquake, RockSlide, Substitute}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey, {IceBeam, Sing, SoftBoiled, ThunderWave}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Explosion, Rest}},
        Init::Set{Species::Sandslash,
                  {Earthquake, RockSlide, Slash, SwordsDance}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Rest, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Jynx, {Blizzard, LovelyKiss, Psychic, Rest}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Rest, SelfDestruct}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Rhydon,
                  {BodySlam, Earthquake, RockSlide, Substitute}},
        Init::Set{Species::Snorlax, {BodySlam, HyperBeam, Reflect, Rest}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Gengar,
                  {Explosion, Hypnosis, MegaDrain, NightShade}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Dragonite, {Agility, Blizzard, HyperBeam, Wrap}},
        Init::Set{Species::Exeggutor,
                  {Explosion, MegaDrain, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, HyperBeam, Reflect, Rest}},
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Snorlax,
                  {Blizzard, BodySlam, HyperBeam, SelfDestruct}},
        Init::Set{Species::Alakazam, {Psychic, Recover, Reflect, ThunderWave}},
        Init::Set{Species::Dragonite, {Agility, Blizzard, HyperBeam, Wrap}},
        Init::Set{Species::Exeggutor,
                  {Explosion, HyperBeam, Psychic, SleepPowder}},
        Init::Set{Species::Lapras, {Blizzard, BodySlam, ConfuseRay, Sing}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, HyperBeam, Thunderbolt}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Arcanine, {BodySlam, FireBlast, HyperBeam, Rest}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, MegaDrain, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Rest, SelfDestruct}},
        Init::Set{Species::Starmie,
                  {Psychic, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Chansey,
                  {SeismicToss, Sing, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, HyperBeam, Psychic, SleepPowder}},
        Init::Set{Species::Rhydon,
                  {BodySlam, Earthquake, RockSlide, Substitute}},
        Init::Set{Species::Snorlax, {BodySlam, IceBeam, Reflect, Rest}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, IceBeam, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Jynx, {Blizzard, LovelyKiss, Psychic, Rest}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Explosion, HyperBeam}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Sandslash,
                  {Earthquake, HyperBeam, Slash, SwordsDance}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, HyperBeam, Thunderbolt}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, HyperBeam, Reflect, Rest}},
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Persian, {BodySlam, BubbleBeam, Slash, Thunderbolt}},
        Init::Set{Species::Snorlax, {BodySlam, Psychic, Reflect, Rest}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Jynx, {Blizzard, Counter, LovelyKiss, Psychic}},
        Init::Set{Species::Chansey,
                  {Counter, IceBeam, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, HyperBeam, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey, {IceBeam, Sing, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, HyperBeam, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {DrillPeck, Thunderbolt, ThunderWave, Toxic}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, IceBeam, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, HyperBeam, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Counter, IceBeam, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Rhydon,
                  {BodySlam, Earthquake, RockSlide, Substitute}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, MegaDrain, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {Amnesia, BodySlam, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie,
                  {Psychic, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Rest, SelfDestruct}},
        Init::Set{Species::Golem,
                  {Earthquake, Explosion, RockSlide, Substitute}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey, {IceBeam, Sing, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, IceBeam, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Jynx, {Blizzard, LovelyKiss, Psychic, Rest}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Snorlax, {BodySlam, IceBeam, Reflect, Rest}},
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Chansey, {IceBeam, Sing, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, IceBeam, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Dragonite, {Blizzard, HyperBeam, ThunderWave, Wrap}},
        Init::Set{Species::Rhydon,
                  {BodySlam, Earthquake, RockSlide, Substitute}},
        Init::Set{Species::Slowbro, {Amnesia, Rest, Surf, ThunderWave}},
        Init::Set{Species::Snorlax, {BodySlam, HyperBeam, Reflect, Rest}},
        Init::Set{Species::Victreebel,
                  {BodySlam, RazorLeaf, SleepPowder, Wrap}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, HyperBeam, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, HyperBeam, Psychic, SleepPowder}},
        Init::Set{Species::Lapras, {Blizzard, HyperBeam, Sing, Thunderbolt}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Rest, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, HyperBeam, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey, {IceBeam, Sing, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, HyperBeam, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey, {IceBeam, Sing, SoftBoiled, ThunderWave}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Explosion, Rest}},
        Init::Set{Species::Exeggutor,
                  {Explosion, MegaDrain, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, HyperBeam, Reflect, Rest}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey, {IceBeam, Sing, SoftBoiled, ThunderWave}},
        Init::Set{Species::Rhydon,
                  {BodySlam, Earthquake, RockSlide, Substitute}},
        Init::Set{Species::Snorlax, {BodySlam, IceBeam, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Lapras, {Blizzard, ConfuseRay, Sing, Thunderbolt}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Jolteon,
                  {DoubleKick, PinMissile, Thunderbolt, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Explosion, Rest}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Rhydon,
                  {BodySlam, Earthquake, RockSlide, Substitute}},
        Init::Set{Species::Slowbro, {Amnesia, Rest, Surf, ThunderWave}},
        Init::Set{Species::Starmie, {Blizzard, Recover, Surf, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey, {IceBeam, Sing, SoftBoiled, ThunderWave}},
        Init::Set{Species::Persian,
                  {BubbleBeam, HyperBeam, Slash, Thunderbolt}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Counter, Earthquake, SelfDestruct}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Alakazam, {Psychic, Recover, Reflect, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Rest, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Rhydon,
                  {BodySlam, Earthquake, RockSlide, Substitute}},
        Init::Set{Species::Snorlax, {BodySlam, HyperBeam, Reflect, Rest}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Starmie,
                  {Psychic, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Jolteon,
                  {DoubleKick, PinMissile, Thunderbolt, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor, {LeechSeed, Psychic, Rest, StunSpore}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, MegaDrain, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Hypno, {Hypnosis, Psychic, Rest, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, MegaDrain, Psychic, SleepPowder}},
        Init::Set{Species::Rhydon,
                  {BodySlam, Earthquake, RockSlide, Substitute}},
        Init::Set{Species::Snorlax, {BodySlam, Earthquake, Reflect, Rest}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Victreebel,
                  {RazorLeaf, SleepPowder, StunSpore, Wrap}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Lapras, {Blizzard, Rest, Sing, Thunderbolt}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Gengar,
                  {Explosion, Hypnosis, NightShade, Thunderbolt}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Slowbro, {Amnesia, Rest, Surf, ThunderWave}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Gengar,
                  {Explosion, Hypnosis, NightShade, Thunderbolt}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Jynx, {Blizzard, LovelyKiss, Psychic, Rest}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Explosion, Rest}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, HyperBeam, TailWhip}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, MegaDrain, Psychic, SleepPowder}},
        Init::Set{Species::Rhydon,
                  {BodySlam, Earthquake, RockSlide, Substitute}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, MegaDrain, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, HyperBeam, Reflect, Rest}},
        Init::Set{Species::Tauros, {Blizzard, BodySlam, Earthquake, HyperBeam}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Jynx, {Blizzard, LovelyKiss, Psychic, Rest}},
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, Reflect, SoftBoiled, Thunderbolt}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {Amnesia, Blizzard, BodySlam, Rest}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Starmie, {Blizzard, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Chansey,
                  {IceBeam, SoftBoiled, Thunderbolt, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {DoubleEdge, Explosion, Psychic, SleepPowder}},
        Init::Set{Species::Gengar,
                  {Explosion, Hypnosis, NightShade, Thunderbolt}},
        Init::Set{Species::Snorlax, {Amnesia, Blizzard, BodySlam, Rest}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    std::array<Init::Set, 6>{
        Init::Set{Species::Jynx, {Blizzard, Counter, LovelyKiss, Psychic}},
        Init::Set{Species::Alakazam, {Counter, Psychic, Recover, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, HyperBeam, Psychic, SleepPowder}},
        Init::Set{Species::Snorlax, {BodySlam, Counter, SelfDestruct, Surf}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, HyperBeam, Thunderbolt}},
        Init::Set{Species::Zapdos,
                  {Agility, DrillPeck, Thunderbolt, ThunderWave}}},
};

} // namespace SampleTeams
