
#pragma once

#include <array>

#include <ii/random-battles/data.h>

namespace RandomBattlesData {

using Data::Species;
using Data::Moves;
using Data::Types;

struct RandomSetEntry {
  static constexpr uint8_t max_moves{9};
  static constexpr uint8_t max_exclusive_moves{9};
  static constexpr uint8_t max_essential_moves{3};
  static constexpr uint8_t max_combo_moves{4};

  uint8_t level;
  uint8_t n_moves;
  uint8_t n_exclusive_moves;
  uint8_t n_essential_moves;
  uint8_t n_combo_moves;

  std::array<Moves, max_moves> moves;
  std::array<Moves, max_exclusive_moves> exclusive_moves;
  std::array<Moves, max_essential_moves> essential_moves;
  std::array<Moves, max_combo_moves> combo_moves;

  std::array<uint8_t, 6> weaknesses{};
  std::array<Types, 2> types{};
};

constexpr std::array<RandomSetEntry, 152> RANDOM_SET_DATA
{

RandomSetEntry{},
// none  not found in data.json
RandomSetEntry{ 89,4,0,0,0,
    {Moves::BodySlam,Moves::RazorLeaf,Moves::SleepPowder,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Bulbasaur), Data::get_types(Species::Bulbasaur)},
RandomSetEntry{ 80,4,0,0,0,
    {Moves::BodySlam,Moves::RazorLeaf,Moves::SleepPowder,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Ivysaur), Data::get_types(Species::Ivysaur)},
RandomSetEntry{ 74,3,3,0,0,
    {Moves::BodySlam,Moves::RazorLeaf,Moves::SleepPowder,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::SwordsDance,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Venusaur), Data::get_types(Species::Venusaur)},
RandomSetEntry{ 90,5,0,2,4,
    {Moves::Counter,Moves::SeismicToss,Moves::SeismicToss,Moves::Slash,Moves::Slash,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::FireBlast,Moves::None},
    {Moves::BodySlam,Moves::FireBlast,Moves::Submission,Moves::SwordsDance},
    getImportantWeaknesses(Species::Charmander), Data::get_types(Species::Charmander)},
RandomSetEntry{ 81,5,0,2,4,
    {Moves::Counter,Moves::SeismicToss,Moves::SeismicToss,Moves::Slash,Moves::Slash,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::FireBlast,Moves::None},
    {Moves::BodySlam,Moves::FireBlast,Moves::Submission,Moves::SwordsDance},
    getImportantWeaknesses(Species::Charmeleon), Data::get_types(Species::Charmeleon)},
RandomSetEntry{ 74,4,0,0,4,
    {Moves::BodySlam,Moves::Earthquake,Moves::FireBlast,Moves::Slash,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::Earthquake,Moves::FireBlast,Moves::HyperBeam,Moves::SwordsDance},
    getImportantWeaknesses(Species::Charizard), Data::get_types(Species::Charizard)},
RandomSetEntry{ 90,2,3,2,0,
    {Moves::BodySlam,Moves::Counter,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::SeismicToss,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Squirtle), Data::get_types(Species::Squirtle)},
RandomSetEntry{ 82,3,3,2,0,
    {Moves::Counter,Moves::Rest,Moves::SeismicToss,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::BodySlam,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Wartortle), Data::get_types(Species::Wartortle)},
RandomSetEntry{ 75,2,3,2,0,
    {Moves::Earthquake,Moves::Rest,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::BodySlam,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Blastoise), Data::get_types(Species::Blastoise)},
RandomSetEntry{},
// caterpie  not found in data.json
RandomSetEntry{},
// metapod  not found in data.json
RandomSetEntry{ 77,3,4,0,0,
    {Moves::Psychic,Moves::SleepPowder,Moves::StunSpore,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::HyperBeam,Moves::MegaDrain,Moves::Substitute,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Butterfree), Data::get_types(Species::Butterfree)},
RandomSetEntry{},
// weedle  not found in data.json
RandomSetEntry{},
// kakuna  not found in data.json
RandomSetEntry{ 81,3,3,0,0,
    {Moves::HyperBeam,Moves::SwordsDance,Moves::Twineedle,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Agility,Moves::Agility,Moves::MegaDrain,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Beedrill), Data::get_types(Species::Beedrill)},
RandomSetEntry{ 90,5,3,1,4,
    {Moves::Agility,Moves::Agility,Moves::QuickAttack,Moves::QuickAttack,Moves::SkyAttack,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::MirrorMove,Moves::SandAttack,Moves::Substitute,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::None,Moves::None},
    {Moves::Agility,Moves::DoubleEdge,Moves::QuickAttack,Moves::SkyAttack},
    getImportantWeaknesses(Species::Pidgey), Data::get_types(Species::Pidgey)},
RandomSetEntry{ 82,5,3,1,4,
    {Moves::Agility,Moves::Agility,Moves::QuickAttack,Moves::QuickAttack,Moves::SkyAttack,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::MirrorMove,Moves::SandAttack,Moves::Substitute,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::None,Moves::None},
    {Moves::Agility,Moves::DoubleEdge,Moves::QuickAttack,Moves::SkyAttack},
    getImportantWeaknesses(Species::Pidgeotto), Data::get_types(Species::Pidgeotto)},
RandomSetEntry{ 76,3,9,0,0,
    {Moves::Agility,Moves::DoubleEdge,Moves::HyperBeam,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::MirrorMove,Moves::Reflect,Moves::SandAttack,Moves::SkyAttack,Moves::SkyAttack,Moves::Substitute,Moves::QuickAttack,Moves::QuickAttack,Moves::QuickAttack},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Pidgeot), Data::get_types(Species::Pidgeot)},
RandomSetEntry{ 89,3,6,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::SuperFang,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::Thunderbolt,Moves::Thunderbolt,Moves::Thunderbolt,Moves::QuickAttack,Moves::QuickAttack,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Rattata), Data::get_types(Species::Rattata)},
RandomSetEntry{ 75,4,0,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::HyperBeam,Moves::SuperFang,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Raticate), Data::get_types(Species::Raticate)},
RandomSetEntry{ 89,3,4,0,0,
    {Moves::Agility,Moves::DoubleEdge,Moves::DrillPeck,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Leer,Moves::Mimic,Moves::MirrorMove,Moves::Substitute,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Spearow), Data::get_types(Species::Spearow)},
RandomSetEntry{ 75,4,0,0,0,
    {Moves::Agility,Moves::DoubleEdge,Moves::DrillPeck,Moves::HyperBeam,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Fearow), Data::get_types(Species::Fearow)},
RandomSetEntry{ 90,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::Glare,Moves::RockSlide,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Ekans), Data::get_types(Species::Ekans)},
RandomSetEntry{ 78,3,3,0,0,
    {Moves::Earthquake,Moves::Glare,Moves::HyperBeam,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::RockSlide,Moves::RockSlide,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Arbok), Data::get_types(Species::Arbok)},
RandomSetEntry{ 87,3,5,0,0,
    {Moves::Surf,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Agility,Moves::BodySlam,Moves::SeismicToss,Moves::SeismicToss,Moves::Thunder,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Pikachu), Data::get_types(Species::Pikachu)},
RandomSetEntry{ 74,3,6,0,0,
    {Moves::Surf,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Agility,Moves::BodySlam,Moves::HyperBeam,Moves::HyperBeam,Moves::SeismicToss,Moves::Thunder,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Raichu), Data::get_types(Species::Raichu)},
RandomSetEntry{ 88,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::RockSlide,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Sandshrew), Data::get_types(Species::Sandshrew)},
RandomSetEntry{ 76,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::RockSlide,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Sandslash), Data::get_types(Species::Sandslash)},
RandomSetEntry{ 90,3,2,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::DoubleKick,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::NidoranF), Data::get_types(Species::NidoranF)},
RandomSetEntry{ 82,3,3,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BubbleBeam,Moves::DoubleEdge,Moves::DoubleKick,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Nidorina), Data::get_types(Species::Nidorina)},
RandomSetEntry{ 74,3,3,0,0,
    {Moves::Blizzard,Moves::Earthquake,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::BodySlam,Moves::Substitute,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Nidoqueen), Data::get_types(Species::Nidoqueen)},
RandomSetEntry{ 90,3,2,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::DoubleKick,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::NidoranM), Data::get_types(Species::NidoranM)},
RandomSetEntry{ 82,3,3,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BubbleBeam,Moves::DoubleEdge,Moves::DoubleKick,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Nidorino), Data::get_types(Species::Nidorino)},
RandomSetEntry{ 74,3,3,2,0,
    {Moves::RockSlide,Moves::Thunderbolt,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::BodySlam,Moves::Substitute,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::Earthquake,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Nidoking), Data::get_types(Species::Nidoking)},
RandomSetEntry{ 88,4,6,2,0,
    {Moves::BodySlam,Moves::BodySlam,Moves::SeismicToss,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::Blizzard,Moves::Counter,Moves::Psychic,Moves::Sing,Moves::Sing,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::ThunderWave,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Clefairy), Data::get_types(Species::Clefairy)},
RandomSetEntry{ 74,5,7,1,0,
    {Moves::BodySlam,Moves::BodySlam,Moves::Thunderbolt,Moves::ThunderWave,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::Counter,Moves::HyperBeam,Moves::HyperBeam,Moves::Psychic,Moves::Sing,Moves::Sing,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Clefable), Data::get_types(Species::Clefable)},
RandomSetEntry{ 88,3,6,0,0,
    {Moves::BodySlam,Moves::ConfuseRay,Moves::FireBlast,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Flamethrower,Moves::Flamethrower,Moves::QuickAttack,Moves::Reflect,Moves::Substitute,Moves::Substitute,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Vulpix), Data::get_types(Species::Vulpix)},
RandomSetEntry{ 74,3,5,0,0,
    {Moves::BodySlam,Moves::ConfuseRay,Moves::FireBlast,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Flamethrower,Moves::HyperBeam,Moves::Reflect,Moves::Substitute,Moves::Substitute,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Ninetales), Data::get_types(Species::Ninetales)},
RandomSetEntry{ 89,3,3,1,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::SeismicToss,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Sing,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::ThunderWave,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Jigglypuff), Data::get_types(Species::Jigglypuff)},
RandomSetEntry{ 76,3,3,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::HyperBeam,Moves::Sing,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Wigglytuff), Data::get_types(Species::Wigglytuff)},
RandomSetEntry{ 100,3,3,0,0,
    {Moves::ConfuseRay,Moves::DoubleEdge,Moves::MegaDrain,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Substitute,Moves::Substitute,Moves::WingAttack,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Zubat), Data::get_types(Species::Zubat)},
RandomSetEntry{ 78,4,0,0,0,
    {Moves::ConfuseRay,Moves::DoubleEdge,Moves::HyperBeam,Moves::MegaDrain,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Golbat), Data::get_types(Species::Golbat)},
RandomSetEntry{ 90,3,3,0,0,
    {Moves::DoubleEdge,Moves::MegaDrain,Moves::SleepPowder,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Oddish), Data::get_types(Species::Oddish)},
RandomSetEntry{ 82,3,3,0,0,
    {Moves::DoubleEdge,Moves::MegaDrain,Moves::SleepPowder,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Gloom), Data::get_types(Species::Gloom)},
RandomSetEntry{ 76,3,3,0,0,
    {Moves::BodySlam,Moves::MegaDrain,Moves::SleepPowder,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Vileplume), Data::get_types(Species::Vileplume)},
RandomSetEntry{ 90,3,3,0,0,
    {Moves::BodySlam,Moves::MegaDrain,Moves::Spore,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Paras), Data::get_types(Species::Paras)},
RandomSetEntry{ 77,3,7,0,0,
    {Moves::BodySlam,Moves::MegaDrain,Moves::Spore,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::Slash,Moves::StunSpore,Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance,Moves::SwordsDance,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Parasect), Data::get_types(Species::Parasect)},
RandomSetEntry{ 88,3,2,0,0,
    {Moves::Psychic,Moves::SleepPowder,Moves::StunSpore,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::MegaDrain,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Venonat), Data::get_types(Species::Venonat)},
RandomSetEntry{ 74,3,2,0,0,
    {Moves::Psychic,Moves::SleepPowder,Moves::StunSpore,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::MegaDrain,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Venomoth), Data::get_types(Species::Venomoth)},
RandomSetEntry{ 86,3,2,0,0,
    {Moves::Earthquake,Moves::RockSlide,Moves::Slash,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::Substitute,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Diglett), Data::get_types(Species::Diglett)},
RandomSetEntry{ 73,3,2,0,0,
    {Moves::Earthquake,Moves::RockSlide,Moves::Slash,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::Substitute,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Dugtrio), Data::get_types(Species::Dugtrio)},
RandomSetEntry{ 85,3,2,0,0,
    {Moves::BodySlam,Moves::BubbleBeam,Moves::Slash,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Thunder,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Meowth), Data::get_types(Species::Meowth)},
RandomSetEntry{ 73,3,4,0,0,
    {Moves::BodySlam,Moves::BubbleBeam,Moves::Slash,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::HyperBeam,Moves::Thunder,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Persian), Data::get_types(Species::Persian)},
RandomSetEntry{ 89,3,5,0,0,
    {Moves::Amnesia,Moves::Blizzard,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::HydroPump,Moves::Rest,Moves::SeismicToss,Moves::SeismicToss,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Psyduck), Data::get_types(Species::Psyduck)},
RandomSetEntry{ 75,3,5,0,0,
    {Moves::Amnesia,Moves::Blizzard,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::HydroPump,Moves::Rest,Moves::Rest,Moves::SeismicToss,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Golduck), Data::get_types(Species::Golduck)},
RandomSetEntry{ 89,3,3,0,0,
    {Moves::BodySlam,Moves::RockSlide,Moves::Submission,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::LowKick,Moves::MegaKick,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Mankey), Data::get_types(Species::Mankey)},
RandomSetEntry{ 76,4,4,2,0,
    {Moves::RockSlide,Moves::RockSlide,Moves::RockSlide,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::LowKick,Moves::HyperBeam,Moves::HyperBeam,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::Submission,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Primeape), Data::get_types(Species::Primeape)},
RandomSetEntry{ 89,3,0,2,0,
    {Moves::Agility,Moves::Flamethrower,Moves::Reflect,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::FireBlast,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Growlithe), Data::get_types(Species::Growlithe)},
RandomSetEntry{ 75,3,6,0,0,
    {Moves::BodySlam,Moves::FireBlast,Moves::HyperBeam,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Agility,Moves::Agility,Moves::Flamethrower,Moves::Flamethrower,Moves::Reflect,Moves::Rest,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Arcanine), Data::get_types(Species::Arcanine)},
RandomSetEntry{ 86,3,4,0,0,
    {Moves::Amnesia,Moves::Blizzard,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Hypnosis,Moves::Hypnosis,Moves::Hypnosis,Moves::Psychic,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Poliwag), Data::get_types(Species::Poliwag)},
RandomSetEntry{ 79,3,5,0,0,
    {Moves::Amnesia,Moves::Blizzard,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Hypnosis,Moves::Hypnosis,Moves::Hypnosis,Moves::Psychic,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Poliwhirl), Data::get_types(Species::Poliwhirl)},
RandomSetEntry{ 74,4,4,1,2,
    {Moves::Blizzard,Moves::BodySlam,Moves::Earthquake,Moves::Submission,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Hypnosis,Moves::Hypnosis,Moves::Hypnosis,Moves::Psychic,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Surf,Moves::None,Moves::None},
    {Moves::Amnesia,Moves::Blizzard,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Poliwrath), Data::get_types(Species::Poliwrath)},
RandomSetEntry{ 84,3,3,0,0,
    {Moves::Psychic,Moves::SeismicToss,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Reflect,Moves::Substitute,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Abra), Data::get_types(Species::Abra)},
RandomSetEntry{ 74,3,5,0,0,
    {Moves::Psychic,Moves::Recover,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Reflect,Moves::Reflect,Moves::SeismicToss,Moves::SeismicToss,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Kadabra), Data::get_types(Species::Kadabra)},
RandomSetEntry{ 68,3,5,0,0,
    {Moves::Psychic,Moves::Recover,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Reflect,Moves::Reflect,Moves::SeismicToss,Moves::SeismicToss,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Alakazam), Data::get_types(Species::Alakazam)},
RandomSetEntry{ 89,3,3,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::Submission,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::RockSlide,Moves::RockSlide,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Machop), Data::get_types(Species::Machop)},
RandomSetEntry{ 81,3,3,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::Submission,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::RockSlide,Moves::RockSlide,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Machoke), Data::get_types(Species::Machoke)},
RandomSetEntry{ 76,3,5,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::Submission,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::HyperBeam,Moves::HyperBeam,Moves::RockSlide,Moves::RockSlide,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Machamp), Data::get_types(Species::Machamp)},
RandomSetEntry{ 88,3,3,0,0,
    {Moves::DoubleEdge,Moves::RazorLeaf,Moves::SleepPowder,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Bellsprout), Data::get_types(Species::Bellsprout)},
RandomSetEntry{ 80,3,3,0,0,
    {Moves::DoubleEdge,Moves::RazorLeaf,Moves::SleepPowder,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Weepinbell), Data::get_types(Species::Weepinbell)},
RandomSetEntry{ 74,3,6,0,0,
    {Moves::BodySlam,Moves::RazorLeaf,Moves::SleepPowder,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::StunSpore,Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance,Moves::SwordsDance,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Victreebel), Data::get_types(Species::Victreebel)},
RandomSetEntry{ 86,3,3,0,0,
    {Moves::Blizzard,Moves::MegaDrain,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Barrier,Moves::HydroPump,Moves::HydroPump,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Tentacool), Data::get_types(Species::Tentacool)},
RandomSetEntry{ 73,3,3,0,0,
    {Moves::Blizzard,Moves::HyperBeam,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Tentacruel), Data::get_types(Species::Tentacruel)},
RandomSetEntry{ 88,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::Explosion,Moves::RockSlide,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Geodude), Data::get_types(Species::Geodude)},
RandomSetEntry{ 80,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::Explosion,Moves::RockSlide,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Graveler), Data::get_types(Species::Graveler)},
RandomSetEntry{ 71,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::Explosion,Moves::RockSlide,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Golem), Data::get_types(Species::Golem)},
RandomSetEntry{ 84,3,6,0,0,
    {Moves::Agility,Moves::BodySlam,Moves::FireBlast,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Reflect,Moves::Reflect,Moves::Reflect,Moves::Stomp,Moves::Substitute,Moves::Substitute,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Ponyta), Data::get_types(Species::Ponyta)},
RandomSetEntry{ 75,4,0,0,0,
    {Moves::Agility,Moves::BodySlam,Moves::FireBlast,Moves::HyperBeam,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Rapidash), Data::get_types(Species::Rapidash)},
RandomSetEntry{ 84,3,3,2,4,
    {Moves::Blizzard,Moves::Psychic,Moves::Rest,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Amnesia,Moves::Earthquake,Moves::Earthquake,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Surf,Moves::ThunderWave,Moves::None},
    {Moves::Amnesia,Moves::Rest,Moves::Surf,Moves::ThunderWave},
    getImportantWeaknesses(Species::Slowpoke), Data::get_types(Species::Slowpoke)},
RandomSetEntry{ 68,3,0,2,4,
    {Moves::Blizzard,Moves::Psychic,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Amnesia,Moves::ThunderWave,Moves::None},
    {Moves::Amnesia,Moves::Rest,Moves::Surf,Moves::ThunderWave},
    getImportantWeaknesses(Species::Slowbro), Data::get_types(Species::Slowbro)},
RandomSetEntry{ 88,3,4,0,0,
    {Moves::Thunder,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::DoubleEdge,Moves::Mimic,Moves::Rest,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Magnemite), Data::get_types(Species::Magnemite)},
RandomSetEntry{ 76,3,5,0,0,
    {Moves::Thunder,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::HyperBeam,Moves::HyperBeam,Moves::Mimic,Moves::Rest,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Magneton), Data::get_types(Species::Magneton)},
RandomSetEntry{ 78,4,0,0,0,
    {Moves::Agility,Moves::BodySlam,Moves::Slash,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Farfetchd), Data::get_types(Species::Farfetchd)},
RandomSetEntry{ 87,4,0,0,0,
    {Moves::Agility,Moves::BodySlam,Moves::DoubleEdge,Moves::DrillPeck,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Doduo), Data::get_types(Species::Doduo)},
RandomSetEntry{ 73,4,0,0,0,
    {Moves::Agility,Moves::BodySlam,Moves::DrillPeck,Moves::HyperBeam,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Dodrio), Data::get_types(Species::Dodrio)},
RandomSetEntry{ 88,4,0,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Rest,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Seel), Data::get_types(Species::Seel)},
RandomSetEntry{ 74,3,4,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::Rest,Moves::Rest,Moves::Rest,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Dewgong), Data::get_types(Species::Dewgong)},
RandomSetEntry{ 90,7,0,2,0,
    {Moves::FireBlast,Moves::FireBlast,Moves::MegaDrain,Moves::Sludge,Moves::Sludge,Moves::Sludge,Moves::Thunderbolt,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::Explosion,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Grimer), Data::get_types(Species::Grimer)},
RandomSetEntry{ 76,9,0,2,0,
    {Moves::FireBlast,Moves::FireBlast,Moves::HyperBeam,Moves::MegaDrain,Moves::MegaDrain,Moves::Sludge,Moves::Sludge,Moves::Sludge,Moves::Thunderbolt},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::Explosion,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Muk), Data::get_types(Species::Muk)},
RandomSetEntry{ 90,4,0,0,0,
    {Moves::Blizzard,Moves::DoubleEdge,Moves::Explosion,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Shellder), Data::get_types(Species::Shellder)},
RandomSetEntry{ 70,3,3,0,0,
    {Moves::Blizzard,Moves::Explosion,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::HyperBeam,Moves::HyperBeam,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Cloyster), Data::get_types(Species::Cloyster)},
RandomSetEntry{ 83,6,0,2,0,
    {Moves::Explosion,Moves::Explosion,Moves::MegaDrain,Moves::NightShade,Moves::Psychic,Moves::Psychic,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Thunderbolt,Moves::Hypnosis,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Gastly), Data::get_types(Species::Gastly)},
RandomSetEntry{ 74,6,0,2,0,
    {Moves::Explosion,Moves::Explosion,Moves::MegaDrain,Moves::NightShade,Moves::Psychic,Moves::Psychic,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Thunderbolt,Moves::Hypnosis,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Haunter), Data::get_types(Species::Haunter)},
RandomSetEntry{ 68,6,0,2,0,
    {Moves::Explosion,Moves::Explosion,Moves::MegaDrain,Moves::NightShade,Moves::Psychic,Moves::Psychic,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Thunderbolt,Moves::Hypnosis,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Gengar), Data::get_types(Species::Gengar)},
RandomSetEntry{ 80,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::Explosion,Moves::RockSlide,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Onix), Data::get_types(Species::Onix)},
RandomSetEntry{ 84,3,5,0,0,
    {Moves::Hypnosis,Moves::Psychic,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Reflect,Moves::Rest,Moves::SeismicToss,Moves::SeismicToss,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Drowzee), Data::get_types(Species::Drowzee)},
RandomSetEntry{ 72,3,6,0,0,
    {Moves::Hypnosis,Moves::Psychic,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Reflect,Moves::Rest,Moves::Rest,Moves::SeismicToss,Moves::SeismicToss,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Hypno), Data::get_types(Species::Hypno)},
RandomSetEntry{ 89,3,4,0,0,
    {Moves::BodySlam,Moves::Crabhammer,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::Blizzard,Moves::Blizzard,Moves::Stomp,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Krabby), Data::get_types(Species::Krabby)},
RandomSetEntry{ 76,4,0,0,0,
    {Moves::BodySlam,Moves::Crabhammer,Moves::HyperBeam,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Kingler), Data::get_types(Species::Kingler)},
RandomSetEntry{ 88,3,2,0,0,
    {Moves::Explosion,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::TakeDown,Moves::Thunder,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Voltorb), Data::get_types(Species::Voltorb)},
RandomSetEntry{ 76,3,5,0,0,
    {Moves::Explosion,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::HyperBeam,Moves::TakeDown,Moves::Thunder,Moves::Thunder,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Electrode), Data::get_types(Species::Electrode)},
RandomSetEntry{ 84,4,0,0,0,
    {Moves::Explosion,Moves::Psychic,Moves::SleepPowder,Moves::StunSpore,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Exeggcute), Data::get_types(Species::Exeggcute)},
RandomSetEntry{ 68,3,6,0,0,
    {Moves::Explosion,Moves::Psychic,Moves::SleepPowder,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::HyperBeam,Moves::MegaDrain,Moves::StunSpore,Moves::StunSpore,Moves::StunSpore,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Exeggutor), Data::get_types(Species::Exeggutor)},
RandomSetEntry{ 89,4,0,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Earthquake,Moves::SeismicToss,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Cubone), Data::get_types(Species::Cubone)},
RandomSetEntry{ 79,4,0,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Earthquake,Moves::SeismicToss,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Marowak), Data::get_types(Species::Marowak)},
RandomSetEntry{ 78,3,5,0,0,
    {Moves::BodySlam,Moves::HighJumpKick,Moves::SeismicToss,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Counter,Moves::Meditate,Moves::MegaKick,Moves::RollingKick,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Hitmonlee), Data::get_types(Species::Hitmonlee)},
RandomSetEntry{ 80,3,5,0,0,
    {Moves::BodySlam,Moves::SeismicToss,Moves::Submission,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Agility,Moves::Agility,Moves::Counter,Moves::Counter,Moves::MegaKick,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Hitmonchan), Data::get_types(Species::Hitmonchan)},
RandomSetEntry{ 78,3,4,0,0,
    {Moves::BodySlam,Moves::HyperBeam,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::Earthquake,Moves::Earthquake,Moves::Earthquake,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Lickitung), Data::get_types(Species::Lickitung)},
RandomSetEntry{ 90,4,0,0,0,
    {Moves::Explosion,Moves::FireBlast,Moves::Sludge,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Koffing), Data::get_types(Species::Koffing)},
RandomSetEntry{ 76,4,0,0,0,
    {Moves::Explosion,Moves::FireBlast,Moves::Sludge,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Weezing), Data::get_types(Species::Weezing)},
RandomSetEntry{ 84,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::RockSlide,Moves::Substitute,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Rhyhorn), Data::get_types(Species::Rhyhorn)},
RandomSetEntry{ 68,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::RockSlide,Moves::Substitute,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Rhydon), Data::get_types(Species::Rhydon)},
RandomSetEntry{ 68,3,7,0,0,
    {Moves::IceBeam,Moves::SoftBoiled,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Reflect,Moves::SeismicToss,Moves::Sing,Moves::Thunderbolt,Moves::Thunderbolt,Moves::Thunderbolt,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Chansey), Data::get_types(Species::Chansey)},
RandomSetEntry{ 74,3,6,0,0,
    {Moves::BodySlam,Moves::MegaDrain,Moves::SleepPowder,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Growth,Moves::StunSpore,Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance,Moves::SwordsDance,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Tangela), Data::get_types(Species::Tangela)},
RandomSetEntry{ 73,3,4,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::HyperBeam,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::RockSlide,Moves::RockSlide,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Kangaskhan), Data::get_types(Species::Kangaskhan)},
RandomSetEntry{ 88,3,3,0,0,
    {Moves::Agility,Moves::Blizzard,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::HydroPump,Moves::Smokescreen,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Horsea), Data::get_types(Species::Horsea)},
RandomSetEntry{ 77,3,4,0,0,
    {Moves::Agility,Moves::Blizzard,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::HydroPump,Moves::HyperBeam,Moves::Smokescreen,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Seadra), Data::get_types(Species::Seadra)},
RandomSetEntry{ 88,4,0,0,0,
    {Moves::Agility,Moves::Blizzard,Moves::DoubleEdge,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Goldeen), Data::get_types(Species::Goldeen)},
RandomSetEntry{ 78,3,0,2,0,
    {Moves::Agility,Moves::DoubleEdge,Moves::HyperBeam,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::Surf,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Seaking), Data::get_types(Species::Seaking)},
RandomSetEntry{ 84,3,3,1,0,
    {Moves::Blizzard,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Recover,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Staryu), Data::get_types(Species::Staryu)},
RandomSetEntry{ 68,5,4,1,0,
    {Moves::Blizzard,Moves::Psychic,Moves::Thunderbolt,Moves::ThunderWave,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Psychic,Moves::Surf,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Recover,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Starmie), Data::get_types(Species::Starmie)},
RandomSetEntry{ 75,4,0,0,0,
    {Moves::Psychic,Moves::SeismicToss,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::MrMime), Data::get_types(Species::MrMime)},
RandomSetEntry{ 75,4,0,0,0,
    {Moves::Agility,Moves::HyperBeam,Moves::Slash,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Scyther), Data::get_types(Species::Scyther)},
RandomSetEntry{ 68,3,5,0,0,
    {Moves::Blizzard,Moves::LovelyKiss,Moves::Psychic,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::Counter,Moves::Counter,Moves::SeismicToss,Moves::Substitute,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Jynx), Data::get_types(Species::Jynx)},
RandomSetEntry{ 74,3,4,0,0,
    {Moves::Psychic,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::SeismicToss,Moves::SeismicToss,Moves::SeismicToss,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Electabuzz), Data::get_types(Species::Electabuzz)},
RandomSetEntry{ 76,3,3,0,0,
    {Moves::BodySlam,Moves::ConfuseRay,Moves::FireBlast,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::Psychic,Moves::SeismicToss,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Magmar), Data::get_types(Species::Magmar)},
RandomSetEntry{ 75,3,3,2,0,
    {Moves::BodySlam,Moves::BodySlam,Moves::Slash,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::SeismicToss,Moves::Submission,Moves::Submission,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::SwordsDance,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Pinsir), Data::get_types(Species::Pinsir)},
RandomSetEntry{ 68,3,4,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::HyperBeam,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::Blizzard,Moves::Blizzard,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Tauros), Data::get_types(Species::Tauros)},
RandomSetEntry{},
// magikarp  not found in data.json
RandomSetEntry{ 74,5,3,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::BodySlam,Moves::HyperBeam,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Gyarados), Data::get_types(Species::Gyarados)},
RandomSetEntry{ 69,4,0,2,0,
    {Moves::BodySlam,Moves::Rest,Moves::Sing,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::Thunderbolt,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Lapras), Data::get_types(Species::Lapras)},
RandomSetEntry{ 100,1,0,0,0,
    {Moves::Transform,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Ditto), Data::get_types(Species::Ditto)},
RandomSetEntry{ 88,5,2,1,0,
    {Moves::DoubleEdge,Moves::DoubleEdge,Moves::QuickAttack,Moves::QuickAttack,Moves::Reflect,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::SandAttack,Moves::TailWhip,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Eevee), Data::get_types(Species::Eevee)},
RandomSetEntry{ 74,3,6,0,0,
    {Moves::Blizzard,Moves::Rest,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::AcidArmor,Moves::BodySlam,Moves::BodySlam,Moves::BodySlam,Moves::HydroPump,Moves::Mimic,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Vaporeon), Data::get_types(Species::Vaporeon)},
RandomSetEntry{ 69,3,5,0,0,
    {Moves::BodySlam,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Agility,Moves::Agility,Moves::DoubleKick,Moves::PinMissile,Moves::PinMissile,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Jolteon), Data::get_types(Species::Jolteon)},
RandomSetEntry{ 76,4,0,0,0,
    {Moves::BodySlam,Moves::FireBlast,Moves::HyperBeam,Moves::QuickAttack,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Flareon), Data::get_types(Species::Flareon)},
RandomSetEntry{ 76,3,4,0,0,
    {Moves::Blizzard,Moves::Recover,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::Psychic,Moves::Thunderbolt,Moves::TriAttack,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Porygon), Data::get_types(Species::Porygon)},
RandomSetEntry{ 87,3,2,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Rest,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Omanyte), Data::get_types(Species::Omanyte)},
RandomSetEntry{ 74,3,2,1,0,
    {Moves::BodySlam,Moves::Rest,Moves::SeismicToss,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Omastar), Data::get_types(Species::Omastar)},
RandomSetEntry{ 88,3,3,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Slash,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Kabuto), Data::get_types(Species::Kabuto)},
RandomSetEntry{ 75,3,2,0,0,
    {Moves::HyperBeam,Moves::Surf,Moves::SwordsDance,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::Slash,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Kabutops), Data::get_types(Species::Kabutops)},
RandomSetEntry{ 75,3,3,0,0,
    {Moves::DoubleEdge,Moves::FireBlast,Moves::HyperBeam,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Agility,Moves::SkyAttack,Moves::SkyAttack,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Aerodactyl), Data::get_types(Species::Aerodactyl)},
RandomSetEntry{ 69,3,2,0,4,
    {Moves::Amnesia,Moves::Blizzard,Moves::BodySlam,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Rest,Moves::SelfDestruct,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::Earthquake,Moves::HyperBeam,Moves::SelfDestruct},
    getImportantWeaknesses(Species::Snorlax), Data::get_types(Species::Snorlax)},
RandomSetEntry{ 70,3,3,0,4,
    {Moves::Agility,Moves::Blizzard,Moves::HyperBeam,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::IceBeam,Moves::Mimic,Moves::Reflect,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::IceBeam,Moves::Reflect,Moves::Rest},
    getImportantWeaknesses(Species::Articuno), Data::get_types(Species::Articuno)},
RandomSetEntry{ 68,4,0,0,0,
    {Moves::Agility,Moves::DrillPeck,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Zapdos), Data::get_types(Species::Zapdos)},
RandomSetEntry{ 73,3,4,0,0,
    {Moves::Agility,Moves::FireBlast,Moves::HyperBeam,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::DoubleEdge,Moves::DoubleEdge,Moves::Reflect,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Moltres), Data::get_types(Species::Moltres)},
RandomSetEntry{ 89,4,0,2,0,
    {Moves::BodySlam,Moves::HyperBeam,Moves::Thunderbolt,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::ThunderWave,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Dratini), Data::get_types(Species::Dratini)},
RandomSetEntry{ 80,4,0,2,0,
    {Moves::BodySlam,Moves::HyperBeam,Moves::Thunderbolt,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::ThunderWave,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Dragonair), Data::get_types(Species::Dragonair)},
RandomSetEntry{ 74,5,0,1,0,
    {Moves::BodySlam,Moves::HyperBeam,Moves::Thunderbolt,Moves::ThunderWave,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Dragonite), Data::get_types(Species::Dragonite)},
RandomSetEntry{ 60,3,4,0,0,
    {Moves::Amnesia,Moves::Psychic,Moves::Recover,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::Thunderbolt,Moves::ThunderWave,Moves::ThunderWave,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Mewtwo), Data::get_types(Species::Mewtwo)},
RandomSetEntry{ 64,6,0,3,0,
    {Moves::Blizzard,Moves::Blizzard,Moves::Earthquake,Moves::Explosion,Moves::Explosion,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Psychic,Moves::SoftBoiled,Moves::ThunderWave},
    {Moves::None,Moves::None,Moves::None,Moves::None},
    getImportantWeaknesses(Species::Mew), Data::get_types(Species::Mew)},
}; // RANDOM_SET_DATA 
}; // namespace RandomSetData
