
#pragma once

#include <array>

#include <data.h>

namespace RandomBattlesData {

using Data::Moves;
using Data::Species;

struct RandomSetEntry {
  static constexpr int max_moves{6};
  static constexpr int max_exclusive_moves{6};
  static constexpr int max_essential_moves{3};
  static constexpr int max_combo_moves{4};

  int level;
  int n_moves;
  int n_essential_moves;
  int n_exclusive_moves;
  int n_combo_moves;

std::array<Moves, max_moves> moves;
std::array<Moves, max_exclusive_moves> exclusive_moves;
std::array<Moves, max_essential_moves> essential_moves;
std::array<Moves, max_combo_moves> combo_moves; 
};

constexpr std::array<RandomSetEntry, 152> RANDOM_SET_DATA
{

RandomSetEntry{},
// none  not found in data.json
RandomSetEntry{ 89,4,0,0,0,
    {Moves::BodySlam,Moves::RazorLeaf,Moves::SleepPowder,Moves::SwordsDance,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 80,4,0,0,0,
    {Moves::BodySlam,Moves::RazorLeaf,Moves::SleepPowder,Moves::SwordsDance,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 74,3,3,0,0,
    {Moves::BodySlam,Moves::RazorLeaf,Moves::SleepPowder,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::SwordsDance,Moves::SwordsDance,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 90,5,0,2,4,
    {Moves::Counter,Moves::SeismicToss,Moves::SeismicToss,Moves::Slash,Moves::Slash,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::FireBlast,Moves::None},
    {Moves::BodySlam,Moves::FireBlast,Moves::Submission,Moves::SwordsDance}},
RandomSetEntry{ 81,5,0,2,4,
    {Moves::Counter,Moves::SeismicToss,Moves::SeismicToss,Moves::Slash,Moves::Slash,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::FireBlast,Moves::None},
    {Moves::BodySlam,Moves::FireBlast,Moves::Submission,Moves::SwordsDance}},
RandomSetEntry{ 74,4,0,0,4,
    {Moves::BodySlam,Moves::Earthquake,Moves::FireBlast,Moves::Slash,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::Earthquake,Moves::FireBlast,Moves::HyperBeam,Moves::SwordsDance}},
RandomSetEntry{ 90,2,3,2,0,
    {Moves::BodySlam,Moves::Counter,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::SeismicToss,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 82,3,3,2,0,
    {Moves::Counter,Moves::Rest,Moves::SeismicToss,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::BodySlam,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 75,2,3,2,0,
    {Moves::Earthquake,Moves::Rest,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::BodySlam,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{},
// caterpie  not found in data.json
RandomSetEntry{},
// metapod  not found in data.json
RandomSetEntry{ 77,3,4,0,0,
    {Moves::Psychic,Moves::SleepPowder,Moves::StunSpore,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::HyperBeam,Moves::MegaDrain,Moves::Substitute,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{},
// weedle  not found in data.json
RandomSetEntry{},
// kakuna  not found in data.json
RandomSetEntry{ 81,3,3,0,0,
    {Moves::HyperBeam,Moves::SwordsDance,Moves::Twineedle,Moves::None,Moves::None,Moves::None},
    {Moves::Agility,Moves::Agility,Moves::MegaDrain,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 90,5,3,1,4,
    {Moves::Agility,Moves::Agility,Moves::QuickAttack,Moves::QuickAttack,Moves::SkyAttack,Moves::None},
    {Moves::MirrorMove,Moves::SandAttack,Moves::Substitute,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::None,Moves::None},
    {Moves::Agility,Moves::DoubleEdge,Moves::QuickAttack,Moves::SkyAttack}},
RandomSetEntry{ 82,5,3,1,4,
    {Moves::Agility,Moves::Agility,Moves::QuickAttack,Moves::QuickAttack,Moves::SkyAttack,Moves::None},
    {Moves::MirrorMove,Moves::SandAttack,Moves::Substitute,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::None,Moves::None},
    {Moves::Agility,Moves::DoubleEdge,Moves::QuickAttack,Moves::SkyAttack}},
RandomSetEntry{ 76,3,9,0,0,
    {Moves::Agility,Moves::DoubleEdge,Moves::HyperBeam,Moves::None,Moves::None,Moves::None},
    {Moves::MirrorMove,Moves::Reflect,Moves::SandAttack,Moves::SkyAttack,Moves::SkyAttack,Moves::Substitute},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 89,3,6,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::SuperFang,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::Thunderbolt,Moves::Thunderbolt,Moves::Thunderbolt,Moves::QuickAttack,Moves::QuickAttack},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 75,4,0,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::HyperBeam,Moves::SuperFang,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 89,3,4,0,0,
    {Moves::Agility,Moves::DoubleEdge,Moves::DrillPeck,Moves::None,Moves::None,Moves::None},
    {Moves::Leer,Moves::Mimic,Moves::MirrorMove,Moves::Substitute,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 75,4,0,0,0,
    {Moves::Agility,Moves::DoubleEdge,Moves::DrillPeck,Moves::HyperBeam,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 90,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::Glare,Moves::RockSlide,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 78,3,3,0,0,
    {Moves::Earthquake,Moves::Glare,Moves::HyperBeam,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::RockSlide,Moves::RockSlide,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 87,3,5,0,0,
    {Moves::Surf,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::Agility,Moves::BodySlam,Moves::SeismicToss,Moves::SeismicToss,Moves::Thunder,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 74,3,6,0,0,
    {Moves::Surf,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::Agility,Moves::BodySlam,Moves::HyperBeam,Moves::HyperBeam,Moves::SeismicToss,Moves::Thunder},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 88,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::RockSlide,Moves::SwordsDance,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 76,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::RockSlide,Moves::SwordsDance,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 90,3,2,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::DoubleKick,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 82,3,3,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None},
    {Moves::BubbleBeam,Moves::DoubleEdge,Moves::DoubleKick,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 74,3,3,0,0,
    {Moves::Blizzard,Moves::Earthquake,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::BodySlam,Moves::Substitute,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 90,3,2,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::DoubleKick,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 82,3,3,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None},
    {Moves::BubbleBeam,Moves::DoubleEdge,Moves::DoubleKick,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 74,3,3,2,0,
    {Moves::RockSlide,Moves::Thunderbolt,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::BodySlam,Moves::Substitute,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::Earthquake,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 88,4,6,2,0,
    {Moves::BodySlam,Moves::BodySlam,Moves::SeismicToss,Moves::Thunderbolt,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::Blizzard,Moves::Counter,Moves::Psychic,Moves::Sing,Moves::Sing},
    {Moves::Blizzard,Moves::ThunderWave,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 74,5,7,1,0,
    {Moves::BodySlam,Moves::BodySlam,Moves::Thunderbolt,Moves::ThunderWave,Moves::ThunderWave,Moves::None},
    {Moves::Blizzard,Moves::Counter,Moves::HyperBeam,Moves::HyperBeam,Moves::Psychic,Moves::Sing},
    {Moves::Blizzard,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 88,3,6,0,0,
    {Moves::BodySlam,Moves::ConfuseRay,Moves::FireBlast,Moves::None,Moves::None,Moves::None},
    {Moves::Flamethrower,Moves::Flamethrower,Moves::QuickAttack,Moves::Reflect,Moves::Substitute,Moves::Substitute},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 74,3,5,0,0,
    {Moves::BodySlam,Moves::ConfuseRay,Moves::FireBlast,Moves::None,Moves::None,Moves::None},
    {Moves::Flamethrower,Moves::HyperBeam,Moves::Reflect,Moves::Substitute,Moves::Substitute,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 89,3,3,1,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::SeismicToss,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Sing,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::ThunderWave,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 76,3,3,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::HyperBeam,Moves::Sing,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 100,3,3,0,0,
    {Moves::ConfuseRay,Moves::DoubleEdge,Moves::MegaDrain,Moves::None,Moves::None,Moves::None},
    {Moves::Substitute,Moves::Substitute,Moves::WingAttack,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 78,4,0,0,0,
    {Moves::ConfuseRay,Moves::DoubleEdge,Moves::HyperBeam,Moves::MegaDrain,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 90,3,3,0,0,
    {Moves::DoubleEdge,Moves::MegaDrain,Moves::SleepPowder,Moves::None,Moves::None,Moves::None},
    {Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 82,3,3,0,0,
    {Moves::DoubleEdge,Moves::MegaDrain,Moves::SleepPowder,Moves::None,Moves::None,Moves::None},
    {Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 76,3,3,0,0,
    {Moves::BodySlam,Moves::MegaDrain,Moves::SleepPowder,Moves::None,Moves::None,Moves::None},
    {Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 90,3,3,0,0,
    {Moves::BodySlam,Moves::MegaDrain,Moves::Spore,Moves::None,Moves::None,Moves::None},
    {Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 77,3,7,0,0,
    {Moves::BodySlam,Moves::MegaDrain,Moves::Spore,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::Slash,Moves::StunSpore,Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 88,3,2,0,0,
    {Moves::Psychic,Moves::SleepPowder,Moves::StunSpore,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::MegaDrain,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 74,3,2,0,0,
    {Moves::Psychic,Moves::SleepPowder,Moves::StunSpore,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::MegaDrain,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 86,3,2,0,0,
    {Moves::Earthquake,Moves::RockSlide,Moves::Slash,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::Substitute,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 73,3,2,0,0,
    {Moves::Earthquake,Moves::RockSlide,Moves::Slash,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::Substitute,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 85,3,2,0,0,
    {Moves::BodySlam,Moves::BubbleBeam,Moves::Slash,Moves::None,Moves::None,Moves::None},
    {Moves::Thunder,Moves::Thunderbolt,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 73,3,4,0,0,
    {Moves::BodySlam,Moves::BubbleBeam,Moves::Slash,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::HyperBeam,Moves::Thunder,Moves::Thunderbolt,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 89,3,5,0,0,
    {Moves::Amnesia,Moves::Blizzard,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::HydroPump,Moves::Rest,Moves::SeismicToss,Moves::SeismicToss,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 75,3,5,0,0,
    {Moves::Amnesia,Moves::Blizzard,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::HydroPump,Moves::Rest,Moves::Rest,Moves::SeismicToss,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 89,3,3,0,0,
    {Moves::BodySlam,Moves::RockSlide,Moves::Submission,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::LowKick,Moves::MegaKick,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 76,4,4,2,0,
    {Moves::RockSlide,Moves::RockSlide,Moves::RockSlide,Moves::Thunderbolt,Moves::None,Moves::None},
    {Moves::Counter,Moves::LowKick,Moves::HyperBeam,Moves::HyperBeam,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::Submission,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 89,3,0,2,0,
    {Moves::Agility,Moves::Flamethrower,Moves::Reflect,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::FireBlast,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 75,3,6,0,0,
    {Moves::BodySlam,Moves::FireBlast,Moves::HyperBeam,Moves::None,Moves::None,Moves::None},
    {Moves::Agility,Moves::Agility,Moves::Flamethrower,Moves::Flamethrower,Moves::Reflect,Moves::Rest},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 86,3,4,0,0,
    {Moves::Amnesia,Moves::Blizzard,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::Hypnosis,Moves::Hypnosis,Moves::Hypnosis,Moves::Psychic,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 79,3,5,0,0,
    {Moves::Amnesia,Moves::Blizzard,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Hypnosis,Moves::Hypnosis,Moves::Hypnosis,Moves::Psychic,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 74,4,4,1,2,
    {Moves::Blizzard,Moves::BodySlam,Moves::Earthquake,Moves::Submission,Moves::None,Moves::None},
    {Moves::Hypnosis,Moves::Hypnosis,Moves::Hypnosis,Moves::Psychic,Moves::None,Moves::None},
    {Moves::Surf,Moves::None,Moves::None},
    {Moves::Amnesia,Moves::Blizzard,Moves::None,Moves::None}},
RandomSetEntry{ 84,3,3,0,0,
    {Moves::Psychic,Moves::SeismicToss,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Reflect,Moves::Substitute,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 74,3,5,0,0,
    {Moves::Psychic,Moves::Recover,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Reflect,Moves::Reflect,Moves::SeismicToss,Moves::SeismicToss,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 68,3,5,0,0,
    {Moves::Psychic,Moves::Recover,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Reflect,Moves::Reflect,Moves::SeismicToss,Moves::SeismicToss,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 89,3,3,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::Submission,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::RockSlide,Moves::RockSlide,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 81,3,3,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::Submission,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::RockSlide,Moves::RockSlide,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 76,3,5,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::Submission,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::HyperBeam,Moves::HyperBeam,Moves::RockSlide,Moves::RockSlide,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 88,3,3,0,0,
    {Moves::DoubleEdge,Moves::RazorLeaf,Moves::SleepPowder,Moves::None,Moves::None,Moves::None},
    {Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 80,3,3,0,0,
    {Moves::DoubleEdge,Moves::RazorLeaf,Moves::SleepPowder,Moves::None,Moves::None,Moves::None},
    {Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 74,3,6,0,0,
    {Moves::BodySlam,Moves::RazorLeaf,Moves::SleepPowder,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::StunSpore,Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance,Moves::SwordsDance},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 86,3,3,0,0,
    {Moves::Blizzard,Moves::MegaDrain,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::Barrier,Moves::HydroPump,Moves::HydroPump,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 73,3,3,0,0,
    {Moves::Blizzard,Moves::HyperBeam,Moves::SwordsDance,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 88,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::Explosion,Moves::RockSlide,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 80,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::Explosion,Moves::RockSlide,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 71,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::Explosion,Moves::RockSlide,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 84,3,6,0,0,
    {Moves::Agility,Moves::BodySlam,Moves::FireBlast,Moves::None,Moves::None,Moves::None},
    {Moves::Reflect,Moves::Reflect,Moves::Reflect,Moves::Stomp,Moves::Substitute,Moves::Substitute},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 75,4,0,0,0,
    {Moves::Agility,Moves::BodySlam,Moves::FireBlast,Moves::HyperBeam,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 84,3,3,2,4,
    {Moves::Blizzard,Moves::Psychic,Moves::Rest,Moves::None,Moves::None,Moves::None},
    {Moves::Amnesia,Moves::Earthquake,Moves::Earthquake,Moves::None,Moves::None,Moves::None},
    {Moves::Surf,Moves::ThunderWave,Moves::None},
    {Moves::Amnesia,Moves::Rest,Moves::Surf,Moves::ThunderWave}},
RandomSetEntry{ 68,3,0,2,4,
    {Moves::Blizzard,Moves::Psychic,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Amnesia,Moves::ThunderWave,Moves::None},
    {Moves::Amnesia,Moves::Rest,Moves::Surf,Moves::ThunderWave}},
RandomSetEntry{ 88,3,4,0,0,
    {Moves::Thunder,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::DoubleEdge,Moves::Mimic,Moves::Rest,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 76,3,5,0,0,
    {Moves::Thunder,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::HyperBeam,Moves::HyperBeam,Moves::Mimic,Moves::Rest,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 78,4,0,0,0,
    {Moves::Agility,Moves::BodySlam,Moves::Slash,Moves::SwordsDance,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 87,4,0,0,0,
    {Moves::Agility,Moves::BodySlam,Moves::DoubleEdge,Moves::DrillPeck,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 73,4,0,0,0,
    {Moves::Agility,Moves::BodySlam,Moves::DrillPeck,Moves::HyperBeam,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 88,4,0,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Rest,Moves::Surf,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 74,3,4,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::Rest,Moves::Rest,Moves::Rest,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 90,7,0,2,0,
    {Moves::FireBlast,Moves::FireBlast,Moves::MegaDrain,Moves::Sludge,Moves::Sludge,Moves::Sludge},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::Explosion,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 76,9,0,2,0,
    {Moves::FireBlast,Moves::FireBlast,Moves::HyperBeam,Moves::MegaDrain,Moves::MegaDrain,Moves::Sludge},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::Explosion,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 90,4,0,0,0,
    {Moves::Blizzard,Moves::DoubleEdge,Moves::Explosion,Moves::Surf,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 70,3,3,0,0,
    {Moves::Blizzard,Moves::Explosion,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::HyperBeam,Moves::HyperBeam,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 83,6,0,2,0,
    {Moves::Explosion,Moves::Explosion,Moves::MegaDrain,Moves::NightShade,Moves::Psychic,Moves::Psychic},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Thunderbolt,Moves::Hypnosis,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 74,6,0,2,0,
    {Moves::Explosion,Moves::Explosion,Moves::MegaDrain,Moves::NightShade,Moves::Psychic,Moves::Psychic},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Thunderbolt,Moves::Hypnosis,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 68,6,0,2,0,
    {Moves::Explosion,Moves::Explosion,Moves::MegaDrain,Moves::NightShade,Moves::Psychic,Moves::Psychic},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Thunderbolt,Moves::Hypnosis,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 80,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::Explosion,Moves::RockSlide,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 84,3,5,0,0,
    {Moves::Hypnosis,Moves::Psychic,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Reflect,Moves::Rest,Moves::SeismicToss,Moves::SeismicToss,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 72,3,6,0,0,
    {Moves::Hypnosis,Moves::Psychic,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Reflect,Moves::Rest,Moves::Rest,Moves::SeismicToss,Moves::SeismicToss},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 89,3,4,0,0,
    {Moves::BodySlam,Moves::Crabhammer,Moves::SwordsDance,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::Blizzard,Moves::Blizzard,Moves::Stomp,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 76,4,0,0,0,
    {Moves::BodySlam,Moves::Crabhammer,Moves::HyperBeam,Moves::SwordsDance,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 88,3,2,0,0,
    {Moves::Explosion,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::TakeDown,Moves::Thunder,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 76,3,5,0,0,
    {Moves::Explosion,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::HyperBeam,Moves::TakeDown,Moves::Thunder,Moves::Thunder,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 84,4,0,0,0,
    {Moves::Explosion,Moves::Psychic,Moves::SleepPowder,Moves::StunSpore,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 68,3,6,0,0,
    {Moves::Explosion,Moves::Psychic,Moves::SleepPowder,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::HyperBeam,Moves::MegaDrain,Moves::StunSpore,Moves::StunSpore,Moves::StunSpore},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 89,4,0,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Earthquake,Moves::SeismicToss,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 79,4,0,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Earthquake,Moves::SeismicToss,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 78,3,5,0,0,
    {Moves::BodySlam,Moves::HighJumpKick,Moves::SeismicToss,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Counter,Moves::Meditate,Moves::MegaKick,Moves::RollingKick,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 80,3,5,0,0,
    {Moves::BodySlam,Moves::SeismicToss,Moves::Submission,Moves::None,Moves::None,Moves::None},
    {Moves::Agility,Moves::Agility,Moves::Counter,Moves::Counter,Moves::MegaKick,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 78,3,4,0,0,
    {Moves::BodySlam,Moves::HyperBeam,Moves::SwordsDance,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::Earthquake,Moves::Earthquake,Moves::Earthquake,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 90,4,0,0,0,
    {Moves::Explosion,Moves::FireBlast,Moves::Sludge,Moves::Thunderbolt,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 76,4,0,0,0,
    {Moves::Explosion,Moves::FireBlast,Moves::Sludge,Moves::Thunderbolt,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 84,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::RockSlide,Moves::Substitute,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 68,4,0,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::RockSlide,Moves::Substitute,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 68,3,7,0,0,
    {Moves::IceBeam,Moves::SoftBoiled,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::Reflect,Moves::SeismicToss,Moves::Sing,Moves::Thunderbolt,Moves::Thunderbolt},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 74,3,6,0,0,
    {Moves::BodySlam,Moves::MegaDrain,Moves::SleepPowder,Moves::None,Moves::None,Moves::None},
    {Moves::Growth,Moves::StunSpore,Moves::StunSpore,Moves::StunSpore,Moves::SwordsDance,Moves::SwordsDance},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 73,3,4,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::HyperBeam,Moves::None,Moves::None,Moves::None},
    {Moves::Counter,Moves::RockSlide,Moves::RockSlide,Moves::Surf,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 88,3,3,0,0,
    {Moves::Agility,Moves::Blizzard,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::HydroPump,Moves::Smokescreen,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 77,3,4,0,0,
    {Moves::Agility,Moves::Blizzard,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::HydroPump,Moves::HyperBeam,Moves::Smokescreen,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 88,4,0,0,0,
    {Moves::Agility,Moves::Blizzard,Moves::DoubleEdge,Moves::Surf,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 78,3,0,2,0,
    {Moves::Agility,Moves::DoubleEdge,Moves::HyperBeam,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::Surf,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 84,3,3,1,0,
    {Moves::Blizzard,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::Recover,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 68,5,4,1,0,
    {Moves::Blizzard,Moves::Psychic,Moves::Thunderbolt,Moves::ThunderWave,Moves::ThunderWave,Moves::None},
    {Moves::HydroPump,Moves::Psychic,Moves::Surf,Moves::Surf,Moves::None,Moves::None},
    {Moves::Recover,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 75,4,0,0,0,
    {Moves::Psychic,Moves::SeismicToss,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 75,4,0,0,0,
    {Moves::Agility,Moves::HyperBeam,Moves::Slash,Moves::SwordsDance,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 68,3,5,0,0,
    {Moves::Blizzard,Moves::LovelyKiss,Moves::Psychic,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::Counter,Moves::Counter,Moves::SeismicToss,Moves::Substitute,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 74,3,4,0,0,
    {Moves::Psychic,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::SeismicToss,Moves::SeismicToss,Moves::SeismicToss,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 76,3,3,0,0,
    {Moves::BodySlam,Moves::ConfuseRay,Moves::FireBlast,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::Psychic,Moves::SeismicToss,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 75,3,3,2,0,
    {Moves::BodySlam,Moves::BodySlam,Moves::Slash,Moves::None,Moves::None,Moves::None},
    {Moves::SeismicToss,Moves::Submission,Moves::Submission,Moves::None,Moves::None,Moves::None},
    {Moves::HyperBeam,Moves::SwordsDance,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 68,3,4,0,0,
    {Moves::BodySlam,Moves::Earthquake,Moves::HyperBeam,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::Blizzard,Moves::Blizzard,Moves::Thunderbolt,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{},
// magikarp  not found in data.json
RandomSetEntry{ 74,5,3,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::BodySlam,Moves::HyperBeam,Moves::Thunderbolt,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 69,4,0,2,0,
    {Moves::BodySlam,Moves::Rest,Moves::Sing,Moves::Surf,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::Thunderbolt,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 100,1,0,0,0,
    {Moves::Transform,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 88,5,2,1,0,
    {Moves::DoubleEdge,Moves::DoubleEdge,Moves::QuickAttack,Moves::QuickAttack,Moves::Reflect,Moves::None},
    {Moves::SandAttack,Moves::TailWhip,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 74,3,6,0,0,
    {Moves::Blizzard,Moves::Rest,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::AcidArmor,Moves::BodySlam,Moves::BodySlam,Moves::BodySlam,Moves::HydroPump,Moves::Mimic},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 69,3,5,0,0,
    {Moves::BodySlam,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::Agility,Moves::Agility,Moves::DoubleKick,Moves::PinMissile,Moves::PinMissile,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 76,4,0,0,0,
    {Moves::BodySlam,Moves::FireBlast,Moves::HyperBeam,Moves::QuickAttack,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 76,3,4,0,0,
    {Moves::Blizzard,Moves::Recover,Moves::ThunderWave,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::Psychic,Moves::Thunderbolt,Moves::TriAttack,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 87,3,2,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Rest,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 74,3,2,1,0,
    {Moves::BodySlam,Moves::Rest,Moves::SeismicToss,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 88,3,3,0,0,
    {Moves::Blizzard,Moves::BodySlam,Moves::Slash,Moves::None,Moves::None,Moves::None},
    {Moves::HydroPump,Moves::Surf,Moves::Surf,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 75,3,2,0,0,
    {Moves::HyperBeam,Moves::Surf,Moves::SwordsDance,Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::Slash,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 75,3,3,0,0,
    {Moves::DoubleEdge,Moves::FireBlast,Moves::HyperBeam,Moves::None,Moves::None,Moves::None},
    {Moves::Agility,Moves::SkyAttack,Moves::SkyAttack,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 69,3,2,0,4,
    {Moves::Amnesia,Moves::Blizzard,Moves::BodySlam,Moves::None,Moves::None,Moves::None},
    {Moves::Rest,Moves::SelfDestruct,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::BodySlam,Moves::Earthquake,Moves::HyperBeam,Moves::SelfDestruct}},
RandomSetEntry{ 70,3,3,0,4,
    {Moves::Agility,Moves::Blizzard,Moves::HyperBeam,Moves::None,Moves::None,Moves::None},
    {Moves::IceBeam,Moves::Mimic,Moves::Reflect,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::IceBeam,Moves::Reflect,Moves::Rest}},
RandomSetEntry{ 68,4,0,0,0,
    {Moves::Agility,Moves::DrillPeck,Moves::Thunderbolt,Moves::ThunderWave,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 73,3,4,0,0,
    {Moves::Agility,Moves::FireBlast,Moves::HyperBeam,Moves::None,Moves::None,Moves::None},
    {Moves::DoubleEdge,Moves::DoubleEdge,Moves::DoubleEdge,Moves::Reflect,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 89,4,0,2,0,
    {Moves::BodySlam,Moves::HyperBeam,Moves::Thunderbolt,Moves::Thunderbolt,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::ThunderWave,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 80,4,0,2,0,
    {Moves::BodySlam,Moves::HyperBeam,Moves::Thunderbolt,Moves::Thunderbolt,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::ThunderWave,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 74,5,0,1,0,
    {Moves::BodySlam,Moves::HyperBeam,Moves::Thunderbolt,Moves::ThunderWave,Moves::ThunderWave,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 60,3,4,0,0,
    {Moves::Amnesia,Moves::Psychic,Moves::Recover,Moves::None,Moves::None,Moves::None},
    {Moves::Blizzard,Moves::Thunderbolt,Moves::ThunderWave,Moves::ThunderWave,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
RandomSetEntry{ 64,6,0,3,0,
    {Moves::Blizzard,Moves::Blizzard,Moves::Earthquake,Moves::Explosion,Moves::Explosion,Moves::Thunderbolt},
    {Moves::None,Moves::None,Moves::None,Moves::None,Moves::None,Moves::None},
    {Moves::Psychic,Moves::SoftBoiled,Moves::ThunderWave},
    {Moves::None,Moves::None,Moves::None,Moves::None}},
}; // RANDOM_SET_DATA 
}; // namespace RandomSetData
